### ISSUE TITLE
Damage automation not functioning (v1.30.9)

### ISSUE THREAD

**Issue by WildBillLives** [Zakarik/foundry-mm3#68]
[fvtt-Actor-decathalon-(uri-andropov)-UEUIHYNsmU6G9yNv.json](https://github.com/Zakarik/foundry-mm3/files/15214305/fvtt-Actor-decathalon-.uri-andropov.-UEUIHYNsmU6G9yNv.json)

[^Example charcter where this issue occurs]

In my M&M3 game the damage automation is not working: I am running Foundry v11.315, M&M3 system v1.30.9

When a PC actor hits a target & I press the "Toughness Roll" button on the chat card I get the following error message:

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'v3')
    at rollVs (common.mjs:2188:73)
common.mjs:2188
```

Notes: Sometimes it will say "reading 'v2', sometimes 'v1', and sometimes 'v3'.  If I click the "Toughness Roll" button multiple times, sometimes it will  eventually roll the save after 6-10 attempts, but it does not apply any injuries to the actor, but will apply effects (like Dazed, Incapacitated, etc)  to the token. Also, when an NPC successfully hits a PC actor there is no 'Toughness Roll" button to click on the chat card. 

I should add it does this with no extra modules loaded, so its not module-related...

**Comment by DeviousHearts** [comment]
I found an issue with this as well. A freind of mine (A genius coder by the name of Ethaks) had to write a world script. the issue was the ownership was not officially recognized by the system, I believe he said. 

I installed the World Scripter module and put this macro in it and it solved the issue for me.

```js
// Fix Toughness Roll Buttons
async function runStuff() {
	const commons = await import("/systems/mutants-and-masterminds-3e/module/helpers/common.mjs");

	Hooks.on("renderChatMessage", async (message, html, data) => {
		html.find("button.btnRoll").click(async (ev) => {
			ev.stopPropagation();
			const target = $(ev.currentTarget);
			const tgt = target.data("target");
			const savetype = target.data("savetype");
			const vs = target.data("vs");
			const dataAtk = target.data("datk");
			const dataStr = target.data("dstr");
			const typeAtk = target.data("type");
			const hasAlt = ev.altKey;

			const token = canvas.scene.tokens.find((token) => token.id === tgt);

			if (token.actor.ownership[game.user.id] === 3 || token.actor.ownership.default === 3) return;
			if (!token.actor.isOwner)
				return ui.notifications.error(`You do not have owner permissions for ${token.actor.name}`);

			const tokenData = token.actor.system;
			const saveScore = tokenData.defense[savetype].total;
			const name = `${game.i18n.localize(CONFIG.MM3.defenses[savetype])}`;

			commons.rollVs(
				token.actor,
				name,
				saveScore,
				vs,
				{ typeAtk: typeAtk, atk: dataAtk, str: dataStr, tkn: token },
				{ alt: hasAlt },
			);
		});
	});
}
runStuff();
```

**Comment by Zakarik** [comment]
Sorry for the delay (and thank you DeviousHearts for answering).

There have been several versions since then, does the bug still exist (without the DeviousHearts script)? If so, I can't import the character from the first post, so if you have character I can import... Thank you.

**Comment by WildBillLives** [comment]
It still does not work for me (the chat card will not roll Toughness save), this with no modules or world scripts loaded. I get the following error however, not the original one (Foundry v12.331, MnM v1.36.9):

```
Error: CONST.CHAT_MESSAGE_STYLES.ROLL is deprecated in favor of defining rolls directly in ChatMessage#rolls
Deprecated since Version 12
Backwards-compatible support will be removed in Version 14
    at Object.logCompatibilityWarning (foundry-esm.js:4609:19)
    at Proxy.get (foundry-esm.js:2505:23)
    at Reflect.get (<anonymous>)
    at Object.get (foundry-esm.js:2493:22)
    at rollAtkTgt (common.mjs:2483:36)
```

**Comment by WildBillLives** [comment]
It actually is working for me now, so I think its fine if you want to close this issue.
