### ISSUE TITLE
Attacks no longer work

### ISSUE THREAD

**Issue by thomasjeffreyandersontwin** [Zakarik/foundry-mm3#82]
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'id')
[Detected 3 packages: system:mutants-and-masterminds-3e(1.36.6), token-action-hud-mm3(1.8.2), token-action-hud-core(1.5.7)]
    at mm.mjs:1358:67
    at Array.filter (<anonymous>)
    at Object.RollMacro (mm.mjs:1358:39)
    at #handleAction (module.js:320:30)
    at RollHandler.handleActionClick (module.js:286:41)
    at RollHandler.handleActionClickCore (roll-handler.js:53:22)
    at actionClick (token-action-hud.js:336:34)
    at HTMLDivElement.<anonymous> (token-action-hud.js:471:13)
    at HTMLDivElement.dispatch (jquery.min.js:2:43184)
    at y.handle (jquery.min.js:2:41168)

**Comment by thomasjeffreyandersontwin** [comment]
Actually I deleted the actor and imported from compendium and everything is fine

**Comment by thomasjeffreyandersontwin** [comment]
Seems the defect only happens through the HUD...

**Comment by Zakarik** [comment]
Sorry for the delay. Is the Token Core HUD the latest version? I've tested it at home and can't reproduce the bug.

If it's still there, can you send a character whose attacks aren't working?
